DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

USE employees_db;

CREATE TABLE department (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Department VARCHAR(30) NOT NULL
);

CREATE TABLE role (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(30) NOT NULL,
  Salary DECIMAL NOT NULL,
  Department_id INT,
  FOREIGN KEY (Department_id)
  REFERENCES Department(id)
  ON DELETE SET NULL
);

CREATE TABLE employee (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  First_name VARCHAR(30) NOT NULL,
  Last_name VARCHAR(30) NOT NULL,
  Role_id INT,
  Manager_id INT,
  FOREIGN KEY (Role_id)
  REFERENCES role(ID)
  ON DELETE SET NULL,
FOREIGN KEY(Manager_id) 
REFERENCES employee(ID)
ON DELETE SET NULL
);